version: "3.7"
services:
  app:
    build:
      args:
        user: tikin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: integrativa
    container_name: erp_integrativa
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rede_erp
  db:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - rede_erp
  nginx:
    image: nginx:alpine
    container_name: nginx_integrativa
    restart: unless-stopped
    ports:
      - 8005:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - rede_erp
networks:
  rede_erp:
    driver: bridge
